### ISSUE TITLE
Clarifying table column output 

### ISSUE THREAD

**Issue by Nikki-Burdett** [VanLoo-lab/gritic#1]
Thanks very much for a nice tool, I was hoping to clarify the column output of the summary tsv:

Below is a snapshot example of a particular gain which has 3 gain indices.
Gain_Index	Timing_Median	Pre_WGD_Probability	Post_WGD_Probability	WGD_Timing_Median
1	0.3480439	0.216	0.784	0.5575
2	0.5267104	0.44	0.56	0.5575
3	0.6638915	0.6947791	0.3052209	0.5575

If I understand correctly, the Gain_Index represents sequential gains in that segment and the Timing_Median is the median of the 250 samples, per Gain_Index). In this case, then, for Gain_Index 1, this suggests that this event (0.348) occurred before WGD (0.5575); however I cannot resolve the Pre_WGD_Probability output with this. 

My interpretation was that the Pre_WGD_Probability column is the ‘probability that this event occurred pre-WGD’, but the output seems contradictory – surely if the event is closer to 0, the probability of Pre_WGD_Probability should be higher than the Post_WGD_Probability?
Or, is this instead ‘the probability that this event would occur by chance pre-WGD’, or something else entirely?

Also a minor point, but the github page says only segments with 10+ SNVs are timed, but the preprint says 20+ - which is correct?

Many thanks,
Nikki

**Comment by tobybaker** [comment]
Hi Nikki, thanks for your comment, there was a bug in the Pre_WGD_Probability column that was fixed in the latest release. The default is now 10 SNVs for timing.
